### PR TITLE
Fix YT link

### PR DESCRIPTION
**Pull request by afkvido**

### CODE REVIEW

**Comment by udu3324** [comment]
Sorry, but YT link was a example of tab. It's not used to promote me.

**Comment by afkvido** [comment]
Alr lol :)
image
what's this then?

**Comment by udu3324** [comment]
that is another example... but credit to me lol
i wanted to make 2 example tabs to make sure the user doesn't forget the , in the array

**Comment by afkvido** [comment]
ok lmao

**Pull request closed without merging**
